cmake_minimum_required(VERSION 3.5.1)

function(generate_vs_filters)
    if(MSVC)
        foreach(absolute_path ${ARGN})
        	string(REPLACE "${CMAKE_CURRENT_SOURCE_DIR}/" "" relative_path ${absolute_path})
        	get_filename_component(relative_dir ${relative_path} DIRECTORY)
            if (NOT "${relative_dir}" STREQUAL "")
                string(REPLACE "/" "\\" filter_name ${relative_dir})
        	    source_group("${filter_name}" FILES ${absolute_path})
            endif()
        endforeach()
    endif()
endfunction()
